#!/bin/bash

#cd /usr/local/lib/python2.6/site-packages/llrffacade
MODULEPATH=`python -c "from distutils.sysconfig import get_python_lib; print get_python_lib()"`
cd $MODULEPATH/llrffacade
#screen -dm -S LlrfFacade-$1 python LlrfFacade.py $*
python LlrfFacade.py $*


